### ISSUE TITLE
C-V2X integration - command line execution is not working

### ISSUE THREAD

**Issue by twardokus** [twardokus/v2verifier#34]
Received report that command line option to use C-V2X is not functioning properly. Follow-up required, possible missing files.

**Comment by twardokus** [comment]
It appears a branch integration was missed in the 2.0 release. Fix planned for next minor version.

**Comment by twardokus** [comment]
Two reports received via email relate to this outstanding issue. A fix is underway and will be released in the next version upgrade, which is currently scheduled for May 2022. Thank you for your patience as we work to repair the C-V2X functionality.

**Comment by CatiaS11** [comment]
> We are awaiting bug fixes in third-party open-source software that V2Verifier relies on for its C-V2X transceiver implementation. For this reason, C-V2X support has been **_temporarily_** removed in version 3.0.0 of V2Verifier. We anticipate releasing a hotfix in the near future to restore C-V2X support.

Hello! 
I was wondering if it was still  possible to still use C-V2X with a previous release of srsRAN? If it is, which release should I install? I understood that it was an issue of srsRAN code, so if I replace the pssch_ue file from the latest release of srsRAN project by the file of any previous release should it work?
Do you have any idea when the bug is going to be fixed?
Thank you!

**Comment by twardokus** [comment]
You may try Ubuntu 18.04 and srsLTE 20.04, which was the last version we knew was working. However, this will break DSRC, since the code for that side requires Python 3 but Ubuntu 18.04 will want to use GNURadio with Python 2 by default. This _should_ be possible, but we are not encouraging it for most people because there are a lot of potential pitfalls in doing that.

Unfortunately, at the moment we do not have any insight into when this bug will be fixed. It is possible that we may have the capacity to patch the C-V2X issue ourselves over the next few months, but this is not guaranteed. If we are able to do that, I will update this issue and a new release of V2Verifier will accordingly be published.
