### ISSUE TITLE
Question: Looking for 1609.2 Certificate Serialization, Contents, and Example

### ISSUE THREAD

**Issue by Kkellarz** [twardokus/v2verifier#57]
Is there anywhere in the v2verifier project where a 1609.2 certificate is verified? (or generated?)

What about the C-OER encoding? Is that encoded or decoded in the v2verifier project?

Thanks team.

**Comment by twardokus** [comment]
Hi - V2Verifier supports certificates, although currently in a limited way. See the `certificates.h` header file for skeletons of the 1609.2-formatted certificates. Additional certificate functionality, including the P2PCD protocol specified by IEEE 1609.2, is currently in development and will be included in the next release of V2Verifier within the next few months. We do use the C-OER encoding, albeit indirectly - the structures and field sizes used for SPDUs and substructures are all designed to comply with the 1609.2 requirements. The `certificates.h` file is also an example of this.
